name: Generate Poem

on:
  workflow_dispatch:
  schedule:
    - cron: '00 20 * * *' # Run every day at 20:00 UTC (starts cheap hour)

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install python-dotenv requests 

      - name: Generate poem
        run: python3 scripts/generate_poem.py

      - name: Commit and push
        run: |
          git config user.name "PoemBot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/ai_poems/
          git commit -m "Poem: $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push
