name: Rebuild Site at PR Midnight

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Bump update log & push
        run: |
          git config user.name  "PoemUpdater"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo "Rebuild $(date -u +'%Y-%m-%d %H:%M')" >> .update_log
          git add .update_log
          git commit -m "Trigger rebuild for show $(date -u +'%Y-%m-%d') poem" || echo "No changes to commit"
          git push
